# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(965, 677)
        mainwindow.setMinimumSize(QtCore.QSize(965, 677))
        mainwindow.setMaximumSize(QtCore.QSize(965, 677))
        mainwindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calcodebtn = QtWidgets.QPushButton(self.centralwidget)
        self.calcodebtn.setGeometry(QtCore.QRect(800, 590, 111, 31))
        self.calcodebtn.setObjectName("calcodebtn")
        self.outvalueshow = QtWidgets.QTextBrowser(self.centralwidget)
        self.outvalueshow.setGeometry(QtCore.QRect(200, 100, 161, 31))
        self.outvalueshow.setObjectName("outvalueshow")
        self.calauthorbtn = QtWidgets.QPushButton(self.centralwidget)
        self.calauthorbtn.setGeometry(QtCore.QRect(780, 100, 111, 31))
        self.calauthorbtn.setObjectName("calauthorbtn")
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar.setGeometry(QtCore.QRect(380, 590, 201, 23))
        self.progressbar.setProperty("value", 0)
        self.progressbar.setObjectName("progressbar")
        self.authorinfoshow = QtWidgets.QTextBrowser(self.centralwidget)
        self.authorinfoshow.setGeometry(QtCore.QRect(620, 210, 231, 81))
        self.authorinfoshow.setObjectName("authorinfoshow")
        self.codevalueshow = QtWidgets.QTextBrowser(self.centralwidget)
        self.codevalueshow.setGeometry(QtCore.QRect(700, 590, 81, 31))
        self.codevalueshow.setObjectName("codevalueshow")
        self.projectinfoshow = QtWidgets.QTextBrowser(self.centralwidget)
        self.projectinfoshow.setGeometry(QtCore.QRect(200, 210, 231, 81))
        self.projectinfoshow.setObjectName("projectinfoshow")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.authorvalueshow = QtWidgets.QTextBrowser(self.centralwidget)
        self.authorvalueshow.setGeometry(QtCore.QRect(720, 150, 141, 31))
        self.authorvalueshow.setObjectName("authorvalueshow")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 20, 441, 16))
        self.label_6.setObjectName("label_6")
        self.invalueshow = QtWidgets.QTextBrowser(self.centralwidget)
        self.invalueshow.setGeometry(QtCore.QRect(200, 150, 161, 31))
        self.invalueshow.setObjectName("invalueshow")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.calprojectbtn = QtWidgets.QPushButton(self.centralwidget)
        self.calprojectbtn.setGeometry(QtCore.QRect(502, 100, 111, 31))
        self.calprojectbtn.setObjectName("calprojectbtn")
        self.authoredit = QtWidgets.QLineEdit(self.centralwidget)
        self.authoredit.setGeometry(QtCore.QRect(710, 50, 181, 31))
        self.authoredit.setObjectName("authoredit")
        self.codeview = QtWidgets.QTextBrowser(self.centralwidget)
        self.codeview.setGeometry(QtCore.QRect(340, 340, 571, 241))
        self.codeview.setObjectName("codeview")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.urledit = QtWidgets.QLineEdit(self.centralwidget)
        self.urledit.setGeometry(QtCore.QRect(200, 50, 411, 31))
        self.urledit.setObjectName("urledit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(340, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(590, 590, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(650, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.catalogshow = QtWidgets.QListWidget(self.centralwidget)
        self.catalogshow.setGeometry(QtCore.QRect(40, 340, 271, 241))
        self.catalogshow.setObjectName("catalogshow")
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.evalrule = QtWidgets.QAction(mainwindow)
        self.evalrule.setObjectName("evalrule")
        self.menu.addAction(self.evalrule)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "github项目评价软件"))
        self.calcodebtn.setText(_translate("mainwindow", "计算代码分数"))
        self.calauthorbtn.setText(_translate("mainwindow", "计算用户分数"))
        self.label_2.setText(_translate("mainwindow", "关系网络分数："))
        self.label_3.setText(_translate("mainwindow", "项目自身分数："))
        self.label_7.setText(_translate("mainwindow", "项目参数："))
        self.label_6.setText(_translate("mainwindow", "输入项目网址          计算时间较长,请耐心等待"))
        self.label_4.setText(_translate("mainwindow", "项目目录："))
        self.label_5.setText(_translate("mainwindow", "用户分数："))
        self.calprojectbtn.setText(_translate("mainwindow", "计算项目分数"))
        self.label_8.setText(_translate("mainwindow", "用户参数："))
        self.urledit.setText(_translate("mainwindow", "https://github.com/tianjin-university/lmis-tieics2017"))
        self.label.setText(_translate("mainwindow", "URL："))
        self.label_10.setText(_translate("mainwindow", "代码浏览："))
        self.label_11.setText(_translate("mainwindow", "代码分数："))
        self.label_9.setText(_translate("mainwindow", "用户："))
        self.menu.setTitle(_translate("mainwindow", "帮助"))
        self.evalrule.setText(_translate("mainwindow", "评分规则"))

